export * from './Acerca'
export * from './Contacto'
export * from './Educacion'
export * from './Footer'
export * from './Habilidades'
export * from './Inicio'
export * from './Navbar'
export * from './Portafolio'
